Feature/fix export status endpoint information
ergonode/backend pull request #1075
Opened 2021-01-18 14:21 UTC by rprzedzik

# Description
Refactor export error mechanisms to be same as in import module

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-01-18 14:25 UTC, wiewiurdp submitted a review, later dismissed

2021-01-18 14:42 UTC, wfajczyk requested changes

2021-01-18 14:42 UTC, wfajczyk commented on module/channel/src/Infrastructure/Persistence/Query/DbalExportQuery.php
> +
Are you sure

2021-01-19 07:49 UTC, piotrkreft requested changes

2021-01-19 07:49 UTC, piotrkreft commented on module/exporter-file/src/Infrastructure/Handler/Export/ProcessMultimediaCommandHandler.php
> +            $this->exportRepository->addError(
I might be wrong but above potentially you are not having an export - Assert will throw an exception and then you are treating it as exportId and trying to persist it.

2021-01-19 07:49 UTC, piotrkreft commented on module/exporter-file/src/Infrastructure/Handler/Export/ProcessMultimediaCommandHandler.php
> +            $this->exportRepository->addError(
If that's not correct it touches other places as well

2021-01-19 07:55 UTC, wiewiurdp approved these changes

2021-01-19 08:56 UTC, wiewiurdp approved these changes

2021-01-19 09:02 UTC, piotrkreft approved these changes

2021-01-19 13:19 UTC, wfajczyk approved these changes

2021-01-19 14:37 UTC, wiewiurdp approved these changes

2021-01-19 14:38 UTC, merged