feature(batch-action) edit attribute value in product
ergonode/backend pull request #1090
Opened 2021-01-25 14:36 UTC by wfajczyk

# Description
Edit attribute value in a product. 

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-01-27 15:26 UTC, wiewiurdp approved these changes

2021-01-28 08:17 UTC, piotrkreft requested changes

2021-01-28 08:17 UTC, piotrkreft commented on module/batch-action/src/Application/Form/Model/BatchActionFormModel.php
> +    public ?array $payload = null;
Isn't it too specific for our case? Possibly other actions will have completely different payload

2021-01-28 08:17 UTC, piotrkreft commented on module/product/src/Infrastructure/Processor/BatchAction/ProductChangeAttributeBatchActionProcessor.php
> +            $command = new ChangeProductAttributesCommand($productId, $attributes);
Action is `product_edit` so I guess EditProductAttributesCommand would be more in place

2021-01-28 12:27 UTC, piotrkreft approved these changes

2021-01-28 12:28 UTC, merged