Allow Value module to be used for more then just Categories (fix #1101)
ergonode/backend pull request #1106
Opened 2021-02-01 14:18 UTC by dankempster

# Description
The Value module can't be used for managing attributes of any entity except for categories.

This PR resolves that by replacing the type hint `Ergonode\SharedKernel\Domain\Aggregate\CategoryId` with`Ergonode\SharedKernel\Domain\AggregateId` for
    - `Ergonode\Value\Domain\EventValueAddedEvent::__construct`
    - `Ergonode\Value\Domain\EventValueChangedEvent::__construct`
    - `Ergonode\Value\Domain\EventRemovedChangedEvent::__construct`

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
To expose the issue I've created `App\` classes and a unit test in a dedicated branch: [dankempster/ergonode-backend:expose-value-module-to-categeory-module-coupling](https://github.com/dankempster/ergonode-backend/tree/expose-value-module-to-categeory-module-coupling).
To run that test, pull down that branch within a `ergonode/docker` environment and run `docker-compose exec php ./bin/phpunit tests/`.

As part of this patch, I've updated the existing unit tests for the modified classes.

- [x] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have ~added~ modified tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-01 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ergonode/backend?pullRequest=1106) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ergonode/backend?pullRequest=1106) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ergonode/backend?pullRequest=1106) it.</sub>

2021-02-01 14:57 UTC, piotrkreft requested changes
Thanks for your contribution and PR! The changes seem appropriate and you are right - the module is meant to be universal - the only downside of this is asymmetric serialization/deserialization from event data but it's not a problem from module perspective.

Please also change composer configuration

2021-02-01 15:41 UTC, dankempster commented
I've updated the composer configuration.

2021-02-02 08:57 UTC, piotrkreft approved these changes

2021-02-02 11:03 UTC, rprzedzik approved these changes

2021-02-02 13:42 UTC, merged