feature(grid) move DbalDataSetFactory outside query objects
ergonode/backend pull request #1113
Opened 2021-02-03 12:53 UTC by rprzedzik

# Description

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [ ] I have read the contribution requirements and fulfill them.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-03 13:11 UTC, piotrkreft approved these changes

2021-02-05 14:46 UTC, wiewiurdp approved these changes

2021-02-08 08:49 UTC, piotrkreft submitted a review, later dismissed

2021-02-08 08:52 UTC, wfajczyk requested changes
Missing changes in `service.yaml` file, in modules:
- Channel
- Comment
- Importer
- Multimedia 
- ProductCollection
- Product
- Segment
- Workflow

2021-02-08 10:44 UTC, wiewiurdp approved these changes

2021-02-08 10:52 UTC, wfajczyk approved these changes

2021-02-08 11:04 UTC, piotrkreft approved these changes

2021-02-08 11:15 UTC, merged