refactor(completeness) change completeness calculation process
ergonode/backend pull request #1266
Opened 2021-03-10 18:19 UTC by rprzedzik

# Description

Refactoring completeness calculation process to increase speed and decrease products calculation repeat

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-11 07:59 UTC, wiewiurdp approved these changes

2021-03-12 08:20 UTC, piotrkreft requested changes

2021-03-12 08:20 UTC, piotrkreft commented on module/completeness/src/Infrastructure/Persistence/Query/CompletenessQuery.php
> +            $count = $query->select('count(*)')
Wouldn't it be reasonable to extract this query out of the loop?

2021-03-12 08:20 UTC, piotrkreft commented on module/completeness/src/Resources/config/services.yml
> +    tags: [ 'ergonode.event_sourcing.projector' ]
Wouldn't it be good to use instaceof if the this is just a local tag? Potentially there could additional nested services.

2021-03-12 08:41 UTC, rprzedzik commented on module/completeness/src/Domain/Calculator/AttributeTemplateElementCompletenessCalculator.php
> +                    && null !== $value) {
for this proces 0 is accepted value

2021-03-12 11:00 UTC, wfajczyk requested changes

2021-03-12 14:20 UTC, piotrkreft approved these changes

2021-03-12 14:32 UTC, wiewiurdp approved these changes

2021-03-12 14:36 UTC, wfajczyk approved these changes

2021-03-12 14:37 UTC, merged