Adding endpoint for status in batch actions
ergonode/backend pull request #1284
Opened 2021-03-15 12:21 UTC by wiewiurdp

# Description
Adding endpoint for status in batch actions 

Issue # 
#1283 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-15 12:30 UTC, rprzedzik approved these changes

2021-03-15 12:34 UTC, wfajczyk requested changes

2021-03-15 12:34 UTC, wfajczyk commented on module/batch-action/src/Infrastructure/Persistence/Query/DbalBatchActionQuery.php
> +            ->setMaxResults(10)
```suggestion
            ->setMaxResults(self::PROFILE_RESOULT)
```
Magick number to const

2021-03-15 12:43 UTC, wfajczyk approved these changes

2021-03-15 14:52 UTC, rprzedzik submitted a review, later dismissed

2021-03-15 14:57 UTC, piotrkreft requested changes

2021-03-15 14:57 UTC, piotrkreft commented on module/batch-action/features/batch-action-notification.feature
> +  Scenario: Get export info
```suggestion
  Scenario: Get batch action info
```

2021-03-15 14:59 UTC, wfajczyk requested changes

2021-03-15 14:59 UTC, wfajczyk commented on module/batch-action/src/Application/Controller/Api/Notification/BatchActionNotificationAction.php
> +     * @IsGranted("CHANNEL_GET_NOTIFICATION")
Channel ?
```
     * @IsGranted("CHANNEL_GET_NOTIFICATION")
```

2021-03-15 14:59 UTC, wfajczyk commented on module/batch-action/src/Resources/config/routes.yml
> +ergonode_channel_notification_api:
```suggestion
ergonode_batch_action_notification_api:
```

2021-03-15 15:31 UTC, piotrkreft approved these changes

2021-03-15 20:20 UTC, wfajczyk approved these changes

2021-03-16 16:51 UTC, rprzedzik approved these changes

2021-03-16 17:02 UTC, merged