Creating validation for adding simple product to variable product
ergonode/backend pull request #1300
Opened 2021-03-19 11:41 UTC by wiewiurdp

# Description
Creating validation for adding simple product to variable product.

Issue # 
#1299 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-23 09:02 UTC, wfajczyk requested changes

2021-03-23 09:02 UTC, wfajczyk commented on module/product/src/Domain/Query/ProductQueryInterface.php
> +
```suggestion
    /**
     * @return AttributeId[]
     */
```

2021-03-23 09:02 UTC, wfajczyk commented on module/product/src/Domain/Query/ProductQueryInterface.php
> +
```suggestion
    /**
     * @return AttributeId[]
     */
```

2021-03-23 13:35 UTC, piotrkreft requested changes

2021-03-23 13:35 UTC, piotrkreft commented on module/product/src/Application/Validator/ProductInvalidChildValidator.php
> +        if (null === $value->childId || !Uuid::isValid($value->childId)) {
```suggestion
        if (null === $value->childId || !ProductId::isValid($value->childId)) {
```

2021-03-23 14:09 UTC, piotrkreft commented on module/product/src/Application/Validator/ProductInvalidChildValidator.php
> +        }, $bindings);
```suggestion
        $bindingsValues = array_map(fn ($attributeId) => $attributeId->getValue(), $bindings);
```

2021-03-25 13:04 UTC, wfajczyk approved these changes

2021-03-25 15:23 UTC, piotrkreft approved these changes

2021-03-25 15:24 UTC, merged