bugfix(product) Adding validation for editing binding attributes in variable product.
ergonode/backend pull request #1306
Opened 2021-03-22 13:47 UTC by wiewiurdp

# Description

Adding validation for editing binding attributes in variable product.

Issue #1305 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-23 08:47 UTC, wfajczyk approved these changes

2021-03-23 12:14 UTC, piotrkreft requested changes

2021-03-23 12:14 UTC, piotrkreft commented on module/product/src/Application/Controller/Api/Bindings/ProductRemoveBindingAction.php
> +        $violations = $this->validator->validate($data, $constraint);
```suggestion
        $violations = $this->validator->validate($data);
```

The model is configured with the constraint, there's no need to pass it manually I think

2021-03-23 12:14 UTC, piotrkreft commented on module/product/src/Application/Validator/ProductHasChildren.php
> +    public string $message = 'Can\'t change binding attribute in product with variations.';
```suggestion
    public string $message = 'Can\'t change binding attribute in product with variants.';
```

I don't think we use variation terminology anywhere?

2021-03-23 12:14 UTC, piotrkreft commented on module/product/src/Application/Validator/ProductHasChildren.php
> +    public function getTargets()
```suggestion
    /**
     * {@inheritdoc}
     */
    public function getTargets(): string
```

2021-03-23 14:30 UTC, piotrkreft approved these changes

2021-03-24 05:40 UTC, wfajczyk approved these changes

2021-03-24 08:44 UTC, merged