refactor(segment) chenge segment calculation process
ergonode/backend pull request #1315
Opened 2021-03-24 14:24 UTC by rprzedzik

# Description

Refactoring segment calculation process by adding custom transport

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-24 14:51 UTC, piotrkreft requested changes

2021-03-24 14:51 UTC, piotrkreft commented on config/packages/messenger.yaml
> +            segment: "segment://"
This probably should be moved as completeness

2021-03-25 08:56 UTC, piotrkreft approved these changes

2021-03-25 10:13 UTC, piotrkreft approved these changes

2021-03-25 10:29 UTC, wfajczyk approved these changes

2021-03-25 11:05 UTC, merged