feature(product) Fixing removing system attributes during import
ergonode/backend pull request #1377
Opened 2021-04-15 09:05 UTC by wiewiurdp

# Description

 Fixing removing system attributes during import

Issue #1376 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
-  #[x] New and existing unit tests pass locally with my changes

2021-04-15 10:16 UTC, rprzedzik requested changes

2021-04-15 10:16 UTC, rprzedzik commented on module/product/src/Domain/Entity/AbstractProduct.php
> +        $systemAttributes = preg_grep('/^esa_[\d]*/', array_keys($this->attributes));
this should be doing outside aggregate not inside ...

2021-04-15 10:37 UTC, rprzedzik approved these changes

2021-04-15 19:01 UTC, piotrkreft requested changes

2021-04-15 19:01 UTC, piotrkreft commented on module/product/src/Domain/Entity/AbstractProduct.php
> +        $systemAttributes = preg_grep('/^esa_[\d]*/', array_keys($this->attributes));
I think, if no better solution we should delimit it to specific attributes - `esa_created_at` etc...

2021-04-16 09:26 UTC, rprzedzik approved these changes

2021-04-16 09:26 UTC, rprzedzik commented on module/importer/src/Infrastructure/Action/AbstractProductImportAction.php
> +    public function getCategories(array $categories): array
It seems to me that this should not be public

2021-04-16 09:26 UTC, rprzedzik commented on module/importer/src/Infrastructure/Action/AbstractProductImportAction.php
> +    public function getChildren(Sku $sku, array $children): array
It seems to me that this should not be public

2021-04-16 09:26 UTC, rprzedzik commented on module/importer/src/Infrastructure/Action/AbstractProductImportAction.php
> +        $systemAttributes = ['esa_status', 'esa_created_at', 'esa_edited_at', 'esa_created_by', 'esa_edited_by'];
Use AttribueType const  eg CreatedBySystemAttribute:TYPE instead of strings

2021-04-16 10:32 UTC, rprzedzik approved these changes

2021-04-16 10:35 UTC, piotrkreft approved these changes

2021-04-16 10:36 UTC, merged