bugfix(workflow) fix incorrect db query for status to product relation
ergonode/backend pull request #1441
Opened 2021-05-17 13:44 UTC by rprzedzik

# Description

Fix incorrect Query that check status attribute relation in products

Issue  #1436
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my change

2021-05-17 13:47 UTC, wiewiurdp approved these changes

2021-05-18 04:56 UTC, wfajczyk approved these changes

2021-05-18 06:29 UTC, piotrkreft requested changes

2021-05-18 06:29 UTC, piotrkreft commented on module/workflow/src/Domain/Query/ProductWorkflowStatusQueryInterface.php
> +    public function findProductIdsByStatusId(StatusId $statusId): array;
This brings incompatibility. Worth documenting somehow?

2021-05-18 12:02 UTC, wfajczyk approved these changes

2021-05-18 12:03 UTC, piotrkreft approved these changes

2021-05-18 12:06 UTC, merged