feature(grid) add POST support
ergonode/backend pull request #1456
Opened 2021-05-26 12:38 UTC by rprzedzik

# Description

Add support for use post in grid requests.

Add new endpoints for support products grid:

GET `api/v1/products/grid' 
POST `api/v1/products/grid' 

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-26 13:01 UTC, piotrkreft requested changes

2021-05-26 13:01 UTC, piotrkreft commented on module/product/src/Application/Controller/Api/ProductGridReadAction.php
>   * @Route("products", methods={"GET"})
Probably can be marked as deprecated?

2021-05-26 13:07 UTC, rprzedzik commented on module/grid/src/PostGridConfiguration.php
> +        $this->field = (string) $request->request->get('field');
It can be nullable, in which case the specific grid can use default values

2021-05-26 13:20 UTC, piotrkreft commented on module/grid/src/PostGridConfiguration.php
> +        $this->field = (string) $request->request->get('field');
But you are casting the value to string - which means it will be an empty string `(true === ('' === (string) null))`

2021-05-26 13:51 UTC, piotrkreft requested changes

2021-05-26 13:51 UTC, piotrkreft commented on module/product/src/Application/Controller/Api/ProductGridReadAction.php
> +     * @SWG\Get(description="This endpoint is depricated, use `GET /api/v1/{language}/products/grid` instead")
deprEcated :) 
You can also add deprecated property = true

2021-05-26 14:17 UTC, wiewiurdp approved these changes

2021-05-27 05:10 UTC, wfajczyk approved these changes

2021-05-27 05:57 UTC, piotrkreft approved these changes

2021-05-27 06:27 UTC, merged