bugfix(segment,workflow) delete condition set after delete object
ergonode/backend pull request #1464
Opened 2021-06-01 10:19 UTC by wfajczyk

# Description
Bugfix delete condition set after delete object workflow transition or segment.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [ ] I have read the contribution requirements and fulfill them.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-01 10:46 UTC, wiewiurdp approved these changes

2021-06-07 12:04 UTC, piotrkreft requested changes

2021-06-07 12:04 UTC, piotrkreft commented on module/workflow/src/Domain/Query/TransitionConditionSetQueryInterface.php
> +interface TransitionConditionSetQueryInterface extends TransitionQueryInterface
It doesn't seem needed to extend the interface to me. Separate interfaces would work just fine

2021-06-08 06:40 UTC, piotrkreft approved these changes

2021-06-08 06:52 UTC, wiewiurdp approved these changes

2021-06-08 07:09 UTC, rprzedzik approved these changes

2021-06-08 07:31 UTC, merged