feature(security) Change Endpoint Privilege Name
ergonode/backend pull request #1487
Opened 2021-06-16 10:29 UTC by wfajczyk

# Description

Issue #1486 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [ ] I have read the contribution requirements and fulfill them.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-06-17 12:38 UTC, piotrkreft requested changes

2021-06-17 12:38 UTC, piotrkreft commented on module/account/src/Application/Security/Voter/UserRoleVoter.php
> +            'Used UserRoleVoter is deprecated and will throw Fatal error in 2.0. You should use ErgonodeRoleVoter',
I'd stick to a more descriptive explanation like that one should use roles starting with `ERGONODE_ROLE_*`

2021-06-18 06:13 UTC, rprzedzik approved these changes

2021-06-18 08:49 UTC, piotrkreft submitted a review, later dismissed

2021-06-18 12:07 UTC, piotrkreft approved these changes

2021-06-18 12:07 UTC, rprzedzik approved these changes

2021-06-21 05:19 UTC, merged