bugfix(importer) - Csv import product relation attribute
ergonode/backend pull request #1505
Opened 2021-07-05 08:51 UTC by wiewiurdp

# Description

Possibility of adding product itself as product relation 

Issue #1504  
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-07-05 09:42 UTC, rprzedzik requested changes

2021-07-05 12:01 UTC, rprzedzik approved these changes

2021-07-06 06:50 UTC, piotrkreft requested changes
The change introduces a lot of BC breaks as far as I see none of which are documented. This should be fixed

2021-07-06 13:19 UTC, rprzedzik submitted a review, later dismissed

2021-07-06 13:24 UTC, piotrkreft requested changes

2021-07-06 13:24 UTC, piotrkreft commented on CHANGELOG.md
> +- bugfix [#1504](https://github.com/ergonode/backend/issues/1504) Possibility of adding product itself as product relation (wiewiurdp)
The bug was not yet introduced to released version therefore there should not be changelog entry for it.

2021-07-07 08:18 UTC, piotrkreft approved these changes

2021-07-07 08:41 UTC, rprzedzik approved these changes

2021-07-07 09:05 UTC, merged