bugfix: fix remove mesages
ergonode/backend pull request #1535
Opened 2021-07-21 11:33 UTC by rprzedzik

# Description

Fix message show when given element can be removed from system. 

Issue 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [ ] I have read the contribution requirements and fulfill them.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-21 12:40 UTC, ochowa requested changes

2021-07-21 12:40 UTC, ochowa commented on module/attribute/src/Infrastructure/Strategy/Relationship/AttributeAttributeGroupRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Attribute group has a relation with attribute';
with an attribute

2021-07-21 12:40 UTC, ochowa commented on module/attribute/src/Infrastructure/Strategy/Relationship/AttributeUnitRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Unit group has a relation with attribute';
an attribute

2021-07-21 12:40 UTC, ochowa commented on module/category/src/Infrastructure/Strategy/Relationship/CategoryInCategoryTreeRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Category has a relation with category tree';
a category tree

2021-07-21 12:40 UTC, ochowa commented on module/designer/src/Infrastructure/Strategy/Relationship/ProductTemplateRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Template has a relation with product';
a product

2021-07-21 12:40 UTC, ochowa commented on module/designer/src/Infrastructure/Strategy/Relationship/TemplateAttributeRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Attribute has a relation with template';
a template

2021-07-21 12:40 UTC, ochowa commented on module/designer/src/Infrastructure/Strategy/Relationship/TemplateMultimediaRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Multimedia has a relation with template';
have a relation with a template. 

Multimedia is plural

2021-07-21 12:40 UTC, ochowa commented on module/designer/src/Infrastructure/Strategy/Relationship/TemplateMultimediaRelationshipStrategy.php
> +    private const MULTIPLE_MESSAGE = 'Multimedia has %count% relations with some templates';
have

2021-07-21 12:40 UTC, ochowa commented on module/exporter-file/src/Infrastructure/Strategy/Relationship/LanguageErgonodeChannelRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Language is used in channel';
a channel

2021-07-21 12:40 UTC, ochowa commented on module/product-collection/src/Infrastructure/Relationship/ProductProductCollectionRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Product has a relation with collection';
a collection

2021-07-21 12:40 UTC, ochowa commented on module/product-collection/src/Infrastructure/Strategy/Relationship/ProductCollectionProductCollectionTypeRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Collection Type has a relation with collection';
a collection

2021-07-21 12:40 UTC, ochowa commented on module/product/src/Infrastructure/Strategy/Relationship/ChildrenProductRelationshipStrategy.php
> +    private const MULTIPLE_MESSAGE = 'Product has %count% relations with others products';
other products

2021-07-21 12:40 UTC, ochowa commented on module/product/src/Infrastructure/Strategy/Relationship/ProductAttributeRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Attribute has a relation with product';
a product

2021-07-21 12:40 UTC, ochowa commented on module/product/src/Infrastructure/Strategy/Relationship/ProductCategoryRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Category has a relation with product';
a product

2021-07-21 12:40 UTC, ochowa commented on module/product/src/Infrastructure/Strategy/Relationship/ProductMultimediaRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Multimedia has a relation with product';
have a relation with a product

2021-07-21 12:40 UTC, ochowa commented on module/product/src/Infrastructure/Strategy/Relationship/ProductMultimediaRelationshipStrategy.php
> +    private const MULTIPLE_MESSAGE = 'Multimedia has %count% relations with some products';
multimedia have

2021-07-21 12:40 UTC, ochowa commented on module/product/src/Infrastructure/Strategy/Relationship/ProductOptionRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Option has a relation with product %sku%';
with a product
+ remove the variable?

2021-07-21 12:40 UTC, ochowa commented on module/product/src/Infrastructure/Strategy/Relationship/ProductRelationAttributeRelationshipStrategy.php
> +    private const MULTIPLE_MESSAGE = 'Product has %count% relations with others products';
other

2021-07-21 12:40 UTC, ochowa commented on module/segment/src/Infrastructure/Strategy/Relationship/ConditionSetSegmentRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Condition set has a relation with segment';
a segment

2021-07-21 12:40 UTC, ochowa commented on module/workflow/src/Infrastructure/Strategy/Relationship/ConditionSetWorkflowTransitionRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Condition set has a relation with transition';
a status transition

2021-07-21 12:40 UTC, ochowa commented on module/workflow/src/Infrastructure/Strategy/Relationship/ConditionSetWorkflowTransitionRelationshipStrategy.php
> +    private const MULTIPLE_MESSAGE = 'Condition set has %count% relations with some transitions';
with some status transitions

2021-07-21 12:40 UTC, ochowa commented on module/workflow/src/Infrastructure/Strategy/Relationship/DefaultStatusRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Status has a relation with workflow';
a workflow

2021-07-21 12:40 UTC, ochowa commented on module/workflow/src/Infrastructure/Strategy/Relationship/StatusProductRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Status has a relation with product';
a product

2021-07-21 12:40 UTC, ochowa commented on module/workflow/src/Infrastructure/Strategy/Relationship/StatusWorkflowRelationshipStrategy.php
> +    private const ONE_MESSAGE = 'Status has a relation with workflow';
a workflow

2021-07-22 09:07 UTC, ochowa approved these changes

2021-07-22 09:48 UTC, wfajczyk approved these changes

2021-07-22 10:16 UTC, bleto approved these changes

2021-07-22 10:25 UTC, merged