Fixing bug with sku index attribute
ergonode/backend pull request #1565
Opened 2021-08-12 14:16 UTC by wiewiurdp

# Description

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [ ] I have read the contribution requirements and fulfill them.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-13 12:40 UTC, piotrkreft requested changes

2021-08-13 12:40 UTC, piotrkreft commented on module/attribute/src/Application/Validator/AttributeCodeValidator.php
> +            SystemAttributeCode::SYSTEM_ATTRIBUTE_PREFIX
Can't we extend AttributeCode value object to deny possibility of creating with `esa_` prefix?

2021-08-17 06:34 UTC, piotrkreft requested changes

2021-08-17 06:34 UTC, piotrkreft commented on module/attribute/src/Domain/ValueObject/AttributeCode.php
> +    public const NOT_SYSTEM_ATTRIBUTE_PATTERN = '/^(?!'.self::SYSTEM_ATTRIBUTE_PREFIX.')[a-zA-Z0-9_]+$/';
it's just a pattern as it was. SystemAttributeCode should have it's own definition and validate by it

2021-08-17 06:34 UTC, piotrkreft commented on module/attribute/tests/Application/Serializer/Normalizer/AttributeNormalizerTest.php
> +        $this->data['code'] = 'esa_system_attribute';
Runtime test specific data should not be set as properties

2021-08-17 06:34 UTC, piotrkreft commented on module/attribute/tests/Application/Serializer/Normalizer/AttributeNormalizerTest.php
> +    public function testShouldDenormalizeAttribute(): void
Missing check of appropriate code setting for system and not system attribute

2021-08-17 11:24 UTC, piotrkreft approved these changes

2021-08-17 12:53 UTC, wfajczyk approved these changes

2021-08-19 12:29 UTC, merged