Adding completeness system attribute
ergonode/backend pull request #1569
Opened 2021-08-18 10:29 UTC by wiewiurdp

# Description

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [ ] I have read the contribution requirements and fulfill them.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-18 11:13 UTC, wfajczyk commented
The attribute will not be created for already running instances. Please repair this bug

2021-08-18 11:15 UTC, wfajczyk requested changes

2021-08-18 11:15 UTC, wfajczyk commented on src/Resources/fixtures/fixture.yaml
> +Ergonode\Completeness\Domain\Entity\Attribute\CompletenessSystemAttribute:
This work only form new instantion

2021-08-19 12:46 UTC, wfajczyk approved these changes

2021-08-19 13:10 UTC, piotrkreft approved these changes

2021-08-20 05:37 UTC, wfajczyk approved these changes

2021-08-20 06:49 UTC, merged