feature(batch action) add autoEndOnError flag to batch action
ergonode/backend pull request #1615
Opened 2021-09-09 13:39 UTC by rprzedzik

# Description

Extend batch action entity witch autoEndOnErrors flag

Issue #1556
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-09 14:14 UTC, wiewiurdp submitted a review, later dismissed

2021-09-09 16:46 UTC, piotrkreft requested changes

2021-09-09 16:46 UTC, piotrkreft commented on module/batch-action/src/Application/Controller/Api/CreateBatchAction.php
> +                    $data->autoEndOnErrors ?: true
Wouldn't it be cleaner to have default true in form model? More reusable that way.

2021-09-09 16:46 UTC, piotrkreft commented on module/batch-action/src/Application/Form/Model/BatchActionFormModel.php
> +    public ?bool $autoEndOnErrors = null;
```suggestion
    public bool $autoEndOnErrors = true;
```

2021-09-10 08:06 UTC, piotrkreft submitted a review, later dismissed

2021-09-10 08:10 UTC, wiewiurdp submitted a review, later dismissed

2021-09-10 08:12 UTC, wfajczyk submitted a review, later dismissed

2021-09-10 08:19 UTC, wiewiurdp approved these changes

2021-09-10 08:19 UTC, piotrkreft approved these changes

2021-09-10 08:22 UTC, wfajczyk approved these changes

2021-09-10 08:24 UTC, merged