feature(batch-action) add reprocessing endpoint
ergonode/backend pull request #1629
Opened 2021-09-15 10:45 UTC by rprzedzik

# Description

Add reprocessing endpoint

Issue #1556
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-15 11:34 UTC, piotrkreft requested changes

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Application/Controller/Api/ReprocessBatchAction.php
> +        $type = $action->getType()->getValue();
If BatchAction is not in `WAITING_FOR_DECISION` status an exception should be thrown

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Application/Controller/Api/ReprocessBatchAction.php
> +     *     response=200,
```suggestion
     *     response=204,
```

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Application/Controller/Api/ReprocessBatchAction.php
> +     *     description="Returns batch information",
Does not return information

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Application/Form/BatchActionCountForm.php
> +            ->add(
Seem redundant

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Application/Form/BatchActionForm.php
> +class BatchActionForm extends AbstractBatchActionForm
If possible I'd remove default forms.

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Application/Form/BatchActionReprocessForm.php
> +class BatchActionReprocessForm extends AbstractBatchActionReprocessForm
If possible I'd remove default form

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Application/Form/Model/BatchActionCountFormModel.php
> +     * @var string|BatchActionFilterFormModel $filter
Seems like `use` is missing

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Application/Form/ReprocessingBatchActionForm.php
> +class ReprocessingBatchActionForm extends AbstractType implements BatchActionFormInterface
It seems redundant

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Domain/Command/ReprocessBatchActionCommand.php
> +        bool $autoEndOnErrors = true
Something off here - value can be nullable if not passed - then should be taken from the current action - this is not done in controller so I assume there's an error somewhere.

2021-09-15 11:34 UTC, piotrkreft commented on module/batch-action/src/Infrastructure/Handler/ReprocessBatchActionCommandHandler.php
> +        $batchAction->setStatus(new BatchActionStatus(BatchActionStatus::PROCESSED));
```suggestion
        $batchAction->setStatus(new BatchActionStatus(BatchActionStatus::PRECESSED));
```
it seems like a typo in status name - I think we do not have PROCESSED one

2021-09-16 06:54 UTC, rprzedzik commented on module/batch-action/src/Application/Form/Model/BatchActionCountFormModel.php
> +     * @var string|BatchActionFilterFormModel $filter
same namspace

2021-09-16 08:04 UTC, wfajczyk submitted a review, later dismissed

2021-09-16 10:27 UTC, piotrkreft requested changes

2021-09-16 10:27 UTC, piotrkreft commented on module/batch-action/src/Application/Form/BatchActionReprocessingFormInterface.php
> +interface BatchActionReprocessingFormInterface
```suggestion
interface BatchActionReprocessFormInterface
```
More in line with abstraction and other classes

2021-09-16 10:57 UTC, piotrkreft approved these changes

2021-09-16 11:03 UTC, wfajczyk approved these changes

2021-09-16 11:05 UTC, merged