feature(import) add multimedia import processor
ergonode/backend pull request #1639
Opened 2021-09-21 13:29 UTC by rprzedzik

# Description

Add multimedia.csv file import processor

Issue #1637
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-09-21 13:32 UTC, wiewiurdp submitted a review, later dismissed

2021-09-22 04:58 UTC, wfajczyk requested changes

2021-09-22 04:58 UTC, wfajczyk commented on module/importer-ergonode-1/src/Infrastructure/Processor/Step/ErgonodeMultimediaProcessorStep.php
> +//        }
Why you added a comment block. 
This looks like a control of added multimedia.

2021-09-22 07:20 UTC, wfajczyk approved these changes

2021-09-22 07:21 UTC, wiewiurdp approved these changes

2021-09-22 07:23 UTC, merged