feature(attribute) - Add attribute code validation
ergonode/backend pull request #1645
Opened 2021-10-05 12:22 UTC by wiewiurdp

# Description

Add attribute code validation

Issue #1644 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-05 12:58 UTC, piotrkreft submitted a review, later dismissed

2021-10-05 13:49 UTC, rprzedzik requested changes

2021-10-05 13:49 UTC, rprzedzik commented on module/attribute/src/Domain/ValueObject/AttributeCode.php
> +    public const FORBIDDEN = ['id'];
Extend Unit test for this class

2021-10-06 07:23 UTC, piotrkreft submitted a review, later dismissed

2021-10-06 08:56 UTC, rprzedzik requested changes

2021-10-06 08:56 UTC, rprzedzik commented on module/attribute/tests/Domain/ValueObject/AttributeCodeTest.php
> +    public function testInvalidString(): void
TestFrobidenString

2021-10-06 09:09 UTC, rprzedzik approved these changes

2021-10-06 10:17 UTC, merged