feature(attribute) add option sorting endpoint
ergonode/backend pull request #1711
Opened 2021-11-08 14:13 UTC by rprzedzik

# Description

Add sorting option endpoint ```PUT /attributes/{attribute}/options/{option}/move```

Issue #1685
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-08 14:54 UTC, wiewiurdp submitted a review, later dismissed

2021-11-09 07:35 UTC, piotrkreft requested changes

2021-11-09 07:35 UTC, piotrkreft commented on module/attribute/features/attribute-multi-select.feature
> +  Scenario: Scenario: Check attribute options sort after adding all
```suggestion
 Scenario: Check attribute options sort after adding all
```

2021-11-09 07:35 UTC, piotrkreft commented on module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionMovedEventProjector.php
> +                var_dump($to);
```suggestion
```

2021-11-09 07:35 UTC, piotrkreft commented on module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionMovedEventProjector.php
> +            var_dump($exception->getMessage());
Probably lots to check still... ;)

2021-11-09 07:35 UTC, piotrkreft commented on module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionMovedEventProjector.php
> +        var_dump('------------------------');
and here

2021-11-09 07:35 UTC, piotrkreft commented on module/attribute/src/Infrastructure/Persistence/Projector/Attribute/DbalAttributeOptionMovedEventProjector.php
> +            var_dump('from '.$from);
here

2021-11-09 12:40 UTC, piotrkreft approved these changes

2021-11-09 12:50 UTC, wiewiurdp approved these changes

2021-11-09 12:50 UTC, merged