feature(core) add dedicated exceptions to DownloaderInterface
ergonode/backend pull request #1745
Opened 2021-11-26 13:43 UTC by rprzedzik

# Description

Add Dedicated exception to DownloadeInterface

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-26 14:43 UTC, piotrkreft requested changes

2021-11-26 14:43 UTC, piotrkreft commented on module/core/src/Infrastructure/Service/CurlDownloader.php
>  class CurlDownloader implements DownloaderInterface
I think this should become deprecated

2021-11-26 14:43 UTC, piotrkreft commented on module/core/src/Infrastructure/Service/GuzzleDownloader.php
> +        $client = new Client();
Should be injected from DI

2021-11-26 14:43 UTC, piotrkreft commented on module/core/src/Infrastructure/Service/GuzzleDownloader.php
> +            $response = $client->request('GET', $url, ['headers' => $this->mapHeaders($headers)]);
```suggestion
            $response = $client->get($url, ['headers' => $this->mapHeaders($headers)]);
```

2021-11-29 12:38 UTC, piotrkreft requested changes

2021-11-29 12:38 UTC, piotrkreft commented on UPGRADE-1.3.md
> +* Remove nullable from `DownloaderInterface` return type
```suggestion
* `DownloaderInterface::download` throws exception rather than returning `null` value
```

2021-11-29 12:48 UTC, wfajczyk submitted a review, later dismissed

2021-11-29 13:02 UTC, piotrkreft approved these changes

2021-11-29 13:02 UTC, wfajczyk approved these changes

2021-11-29 13:05 UTC, merged