Workflow provider refactoring
ergonode/backend pull request #1753
Opened 2021-12-01 10:01 UTC by rprzedzik

# Description

Refactoring of Workflow provider for language context usage

Issue #1752
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-12-01 11:54 UTC, piotrkreft submitted a review, later dismissed

2021-12-01 12:00 UTC, wfajczyk requested changes

2021-12-01 12:00 UTC, wfajczyk commented on module/workflow/src/Domain/Query/TransitionQueryInterface.php
> +    public function findWorkflowsByStatus(StatusId $statusId): array;
This is an incompatible change

2021-12-01 13:43 UTC, wfajczyk approved these changes

2021-12-02 08:20 UTC, wfajczyk approved these changes

2021-12-02 08:21 UTC, piotrkreft approved these changes

2021-12-02 08:25 UTC, merged