refactor(completeness) Change completeness first save after create new product
ergonode/backend pull request #1832
Opened 2022-01-03 13:38 UTC by wfajczyk

# Description

Issue #1831 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [ ] I have read the contribution requirements and fulfill them.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-03 13:54 UTC, wiewiurdp approved these changes

2022-01-03 14:31 UTC, piotrkreft requested changes
CompletenessSystemAttributeDataSetQueryBuilder needs a simplification as well and removal of coalesce

2022-01-04 07:11 UTC, wfajczyk commented
I left the condition in `CompletenessSystemAttributeDataSetQueryBuilder` because I have the exact same problem when changing the language tree

2022-01-04 10:14 UTC, rprzedzik approved these changes

2022-01-04 10:29 UTC, wiewiurdp approved these changes

2022-01-04 12:10 UTC, piotrkreft approved these changes

2022-01-05 07:53 UTC, merged