feature(core) extend downloader at accept types
ergonode/backend pull request #1833
Opened 2022-01-07 08:24 UTC by wfajczyk

# Description

Issue # 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [ ] I have read the contribution requirements and fulfill them.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-01-07 08:36 UTC, rprzedzik commented
I seem to be missing the passed configuration with restricted types

2022-01-07 08:37 UTC, rprzedzik requested changes

2022-01-07 08:37 UTC, rprzedzik commented on module/core/src/Infrastructure/Service/Decorator/CacheDownloaderDecorator.php
> +    public function download(string $url, array $headers = [], string $acceptedHeaderTypes = null): string
As far as I know it is about limiting the allowed mime formats ? So maybe it is better to call it AcceptedMimeTypes or AcceptetContenType ?

2022-01-07 08:37 UTC, rprzedzik commented on module/core/src/Infrastructure/Service/CurlDownloader.php
> +    public function download(string $url, array $headers = [], string $acceptedHeaderTypes = null): string
IMHO acceptedHeaderTypes should be array not string, or I miss somthing ??

2022-01-10 09:35 UTC, rprzedzik requested changes

2022-01-10 09:35 UTC, rprzedzik commented on module/core/src/Infrastructure/Exception/NotAcceptedHeaderTypeException.php
> +    public function __construct(array $headerType)
Ad phpdoc string[]

2022-01-10 09:35 UTC, rprzedzik commented on module/core/src/Infrastructure/Service/CurlDownloader.php
> +    public function download(string $url, array $headers = [], array $acceptedContentTypes = null): string
Set default value as  empty array instead of null

2022-01-10 09:35 UTC, rprzedzik commented on module/core/src/Infrastructure/Service/CurlDownloader.php
> +        if (null !== $acceptedContentTypes) {
IS needed to throw exception ?? 
If this class not use the simple don use it ??

2022-01-10 09:35 UTC, rprzedzik commented on module/core/src/Infrastructure/Service/GuzzleDownloader.php
> +    private function validateContentType(array $mimeTypes, ?array $acceptedContentTypes): void
IMHO nullable array is not good idea

2022-01-10 09:35 UTC, rprzedzik commented on module/multimedia/src/Infrastructure/Provider/MultimediaExtensionProvider.php
> +        return [
Wouldn't creating a relationship dictionary between extension and mime type be better ??

2022-01-12 10:34 UTC, rprzedzik approved these changes

2022-01-12 10:35 UTC, piotrkreft approved these changes

2022-01-21 06:53 UTC, merged