bug(language tree) fixing bug with category tree privileges
ergonode/backend pull request #726
Opened 2020-09-04 12:11 UTC by wiewiurdp

# Description

Fixing bug with category tree privileges

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-09-07 07:15 UTC, rprzedzik approved these changes

2020-09-07 09:21 UTC, piotrkreft requested changes

2020-09-07 09:21 UTC, piotrkreft commented on module/core/src/Application/Controller/Api/LanguageTree/LanguageTreeReadAction.php
> -     * @IsGranted("SETTINGS_READ")
Class import is therefore redundant I guess :)

2020-09-07 09:33 UTC, piotrkreft approved these changes

2020-09-08 04:43 UTC, wfajczyk approved these changes

2020-09-08 06:24 UTC, merged