feature(product) Adding grid with children and available products for variable products
ergonode/backend pull request #783
Opened 2020-09-23 08:04 UTC by wiewiurdp

# Description

Adding grid with children and available products for variable products.

Issue #766 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-09-23 11:04 UTC, piotrkreft requested changes

2020-09-23 11:04 UTC, piotrkreft commented on module/product/src/Persistence/Dbal/Query/DbalProductChildrenQuery.php
> +        array $bindings,
You could just pass Product but up to U ;)

2020-09-23 11:04 UTC, piotrkreft commented on module/product/src/Application/Controller/Api/Relations/VariableProductAvailableChildrenAction.php
> +        Assert::isInstanceOf($product, VariableProduct::class);
There's just one issue with it. It seems like the exception thrown internally causes 500 server error. Maybe it's worth considering?

2020-09-24 11:27 UTC, piotrkreft approved these changes

2020-09-24 12:24 UTC, rprzedzik approved these changes

2020-09-24 12:25 UTC, merged