bug(product) Fixing unique multiselect option and empty option
ergonode/backend pull request #813
Opened 2020-10-05 23:37 UTC by wiewiurdp

# Description

Fixing unique multiselect option and empty option

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-10-06 06:30 UTC, piotrkreft requested changes

2020-10-06 06:30 UTC, piotrkreft commented on module/attribute/src/Infrastructure/Provider/Strategy/OptionAttributeValueConstraintStrategy.php
> +            ], ];
New line lost :)

2020-10-06 07:01 UTC, rprzedzik requested changes

2020-10-06 07:01 UTC, rprzedzik commented on module/product/src/Infrastructure/Persistence/Projector/DbalProductValueChangedEventProjector.php
> +                if ($phrase) {
This is not a solution, this only ensures that an empty value is not saved in this projector.
Empty value will remain in the domain object and will appear in other projectors based on this event.

2020-10-07 07:00 UTC, piotrkreft approved these changes

2020-10-07 09:14 UTC, rprzedzik approved these changes

2020-10-07 10:07 UTC, rprzedzik approved these changes

2020-10-07 10:35 UTC, merged