Adding binding collumns to available products grid and fixing filtering
ergonode/backend pull request #823
Opened 2020-10-09 08:15 UTC by wiewiurdp

# Description

Adding binding collumns to available products grid and fixing filtering

Issue #766 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-10-09 08:22 UTC, rprzedzik submitted a review, later dismissed

2020-10-09 08:26 UTC, wfajczyk requested changes

2020-10-09 08:26 UTC, wfajczyk commented on module/product/features/associated-product-available-children-grid.feature
> +
`Then` ?

2020-10-09 10:50 UTC, piotrkreft requested changes

2020-10-09 10:50 UTC, piotrkreft commented on module/product/src/Application/Controller/Api/Relations/AssociatedProductAvailableChildrenAction.php
> +            foreach ($bindings as $binding) {
Can all be loaded at once

2020-10-09 10:50 UTC, piotrkreft commented on module/product/src/Infrastructure/Persistence/Query/DbalProductChildrenQuery.php
> +                $bindingAttribute->getId(),
Those should be bound to query, not used as strings directly

2020-10-12 07:44 UTC, piotrkreft approved these changes

2020-10-12 07:44 UTC, rprzedzik approved these changes

2020-10-12 07:45 UTC, wfajczyk approved these changes

2020-10-12 07:45 UTC, merged