refactoring(attribute) move attribute value maping to dedicated service
ergonode/backend pull request #894
Opened 2020-10-29 13:37 UTC by rprzedzik

# Description

Add separate mapping service for prevent use incorrect valued in given attribute type

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-10-29 15:02 UTC, piotrkreft requested changes

2020-10-30 09:56 UTC, wfajczyk requested changes

2020-10-30 09:56 UTC, wfajczyk commented on module/attribute/src/Infrastructure/Mapper/Strategy/TextAttributeMapperStrategy.php
> +                Assert::maxLength($value, 256);
Change to 255

2020-10-30 14:01 UTC, piotrkreft approved these changes

2020-10-31 16:55 UTC, wfajczyk approved these changes

2020-10-31 16:55 UTC, merged