feature(account) user valiadator
ergonode/backend pull request #897
Opened 2020-11-02 11:07 UTC by wfajczyk

# Description
Change response about user validation 

Issue # 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-11-02 11:35 UTC, rprzedzik submitted a review, later dismissed

2020-11-02 11:36 UTC, piotrkreft submitted a review, later dismissed

2020-11-02 11:42 UTC, wiewiurdp requested changes

2020-11-02 11:42 UTC, wiewiurdp commented on module/account/features/account.feature
> +  Scenario: Create user (to long mail)
you mean "too long mail" ?

2020-11-03 07:25 UTC, piotrkreft approved these changes

2020-11-03 08:48 UTC, wiewiurdp approved these changes

2020-11-03 09:03 UTC, merged