bug(attribute) Adding type filter to attribute autocomplete endpoint
ergonode/backend pull request #903
Opened 2020-11-03 13:58 UTC by wiewiurdp

# Description

Adding type filter to attribute autocomplete endpoint

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-11-03 14:01 UTC, rprzedzik submitted a review, later dismissed

2020-11-03 14:11 UTC, wfajczyk requested changes

2020-11-03 14:11 UTC, wfajczyk commented on module/attribute/src/Infrastructure/Persistence/Query/DbalAttributeQuery.php
>              $query->orWhere('code ILIKE :search');
Are you sure in this place is `orWhere` ? 
I thin about parse where 
```
WHERE 
type = 'type' 
OR code ILIKE 'search '
```

2020-11-03 14:59 UTC, wfajczyk approved these changes

2020-11-04 07:35 UTC, rprzedzik approved these changes

2020-11-04 07:35 UTC, merged