bug(condition) Adding langauge to product has status condition
ergonode/backend pull request #964
Opened 2020-11-17 16:16 UTC by wiewiurdp

# Description

 Adding langauge to product has status condition

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [x] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-11-17 20:15 UTC, wfajczyk commented
You don't added migration for currently stored conditions.

2020-11-20 11:36 UTC, piotrkreft requested changes

2020-11-20 11:36 UTC, piotrkreft commented on module/condition/migrations/Version20201119103017.php
> +                SELECT id, (\'{\'|| arr.position -1 || \',language}\')::text[] as path
Is there any specific reason for not extracting just position and creating this in `jsonb_set` function? I'd rather have it like that

2020-11-20 11:36 UTC, piotrkreft commented on module/condition/migrations/Version20201119103017.php
> +            set conditions = jsonb_set(conditions, conditions_list.path, \'%s\')
Please write language constructs (like `set`)  with the upper case in the entire query and not just parts of it. Also reformat it - i.e. in this line indentation is missing

2020-11-20 11:36 UTC, piotrkreft commented on module/condition/migrations/Version20201119103017.php
> +            'WITH conditions_list as (
Here as in above.

2020-11-20 11:36 UTC, piotrkreft commented on module/condition/migrations/Version20201119103017.php
> +        $qb = $this->connection->createQueryBuilder()
In fact, you don't need the connection service to execute the query. Just add the appropriate SQL to the above queries.

2020-11-20 11:36 UTC, piotrkreft commented on module/condition/src/Infrastructure/Condition/Calculator/ProductHasStatusConditionCalculatorStrategy.php
> +        foreach ($filteredProductStatuses as $filteredProductStatus) {
Multiple iterations over the same array occur - maybe worth reducing?

2020-11-23 07:43 UTC, rprzedzik submitted a review, later dismissed

2020-11-23 11:16 UTC, wfajczyk approved these changes

2020-11-23 11:51 UTC, wfajczyk approved these changes

2020-11-23 12:59 UTC, piotrkreft approved these changes

2020-11-23 13:00 UTC, merged