Rrefactoring abstract dbal data set
ergonode/backend pull request #986
Opened 2020-11-26 08:46 UTC by wiewiurdp

# Description

Rrefactoring abstract dbal data set

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-12-01 10:14 UTC, piotrkreft requested changes

2020-12-01 10:14 UTC, piotrkreft commented on module/grid/src/Application/DependencyInjection/CompilerPass/FilterBuilderCompilerPass.php
> +    public const TAG = 'component.grid.builder.filter';
Please use configuration over compiler pass

2020-12-02 10:16 UTC, piotrkreft approved these changes

2020-12-02 12:08 UTC, wfajczyk approved these changes

2020-12-02 12:09 UTC, merged