bugfix(exporter)Shopware6 Customfield Translate
ergonode/backend pull request #987
Opened 2020-11-26 13:03 UTC by wfajczyk

# Description
Fix update translation CustomFiled in Shopware6.
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-11-26 13:36 UTC, rprzedzik approved these changes

2020-11-26 15:43 UTC, piotrkreft requested changes

2020-11-26 15:43 UTC, piotrkreft commented on module/exporter-shopware-6/src/Infrastructure/Model/AbstractShopware6CustomFieldConfig.php
> +            $newLabel = array_merge($this->label, $label);
The method stops being setter after this.

2020-11-27 09:52 UTC, piotrkreft approved these changes

2020-11-27 10:28 UTC, rprzedzik approved these changes

2020-11-27 11:16 UTC, piotrkreft approved these changes

2020-11-27 11:16 UTC, merged