bugfix(Core) Removing incorrect relations with the product module
ergonode/backend pull request #993
Opened 2020-11-28 09:41 UTC by rprzedzik

# Description

Fix incorrect relation from Module Core to module Product

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-12-02 10:18 UTC, piotrkreft commented
It'd be great to fix deptrac configuration once done 👍🏻

2020-12-03 09:25 UTC, piotrkreft requested changes
Could you fix the relation in deptrac as well, please?

2020-12-03 09:30 UTC, piotrkreft approved these changes

2020-12-03 09:35 UTC, wfajczyk approved these changes

2020-12-03 09:48 UTC, merged